// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYvVTHeDRGPcIh4O4bh2olCmMy4G6ZTmk',
    appId: '1:310030934301:web:d4205a49b4ca233fd241f4',
    messagingSenderId: '310030934301',
    projectId: 'bayanat-task',
    authDomain: 'bayanat-task.firebaseapp.com',
    storageBucket: 'bayanat-task.firebasestorage.app',
    measurementId: 'G-01TH0N83FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANp4_bt20r2JkP0M3p-e0wR3OYyq16wfY',
    appId: '1:310030934301:android:9d78ed4bc7c0f467d241f4',
    messagingSenderId: '310030934301',
    projectId: 'bayanat-task',
    storageBucket: 'bayanat-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdQ5AJfo3q2kHR_vNLqxN8uySpi8-3es',
    appId: '1:310030934301:ios:db362c75cb0307a2d241f4',
    messagingSenderId: '310030934301',
    projectId: 'bayanat-task',
    storageBucket: 'bayanat-task.firebasestorage.app',
    iosBundleId: 'com.example.taskBayanat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdQ5AJfo3q2kHR_vNLqxN8uySpi8-3es',
    appId: '1:310030934301:ios:db362c75cb0307a2d241f4',
    messagingSenderId: '310030934301',
    projectId: 'bayanat-task',
    storageBucket: 'bayanat-task.firebasestorage.app',
    iosBundleId: 'com.example.taskBayanat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYvVTHeDRGPcIh4O4bh2olCmMy4G6ZTmk',
    appId: '1:310030934301:web:5047808d45a3683fd241f4',
    messagingSenderId: '310030934301',
    projectId: 'bayanat-task',
    authDomain: 'bayanat-task.firebaseapp.com',
    storageBucket: 'bayanat-task.firebasestorage.app',
    measurementId: 'G-CP4QTQH4YH',
  );
}
